"""首次启动向导；缺 ~/.sanshiliu/.env 时引导填 3 项 LLM 配置并测试连通。"""

from __future__ import annotations

import asyncio
import os
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from pathlib import Path

from sanshiliu.foundation.logging import get_logger


def _mkdir_parents(p: Path) -> None:
    """单独函数以便从 async 上下文用 to_thread 调度（绕 ASYNC240）。"""
    p.mkdir(parents=True, exist_ok=True)

_logger = get_logger(__name__)

# 与 config.Settings 字段一一对应；wizard 按此顺序问
_REQUIRED_KEYS: tuple[tuple[str, str, str], ...] = (
    # (env_name, prompt_text, default)
    ("OPENAI_API_KEY", "OpenAI 兼容后端 API Key", ""),
    ("OPENAI_BASE_URL", "OpenAI 兼容后端 base URL", "https://api.openai.com/v1"),
    ("OPENAI_MODEL", "模型 ID（gpt-4o-mini / deepseek-chat / glm-4 等）", "gpt-4o-mini"),
)


@dataclass
class WizardResult:
    """向导产出；env_path 是 ~/.sanshiliu/.env，values 是采集到的 3 项配置。"""

    env_path: Path
    values: dict[str, str]
    llm_ok: bool
    llm_error: str = ""


def _is_env_complete(env_path: Path) -> bool:
    """env 文件 + 进程环境变量任一来源能凑齐 3 项必填时返回 True。"""
    parsed: dict[str, str] = {}
    if env_path.is_file():
        text = env_path.read_text(encoding="utf-8")
        for line in text.splitlines():
            s = line.strip()
            if not s or s.startswith("#") or "=" not in s:
                continue
            k, _, v = s.partition("=")
            parsed[k.strip()] = v.strip().strip('"').strip("'")
    for key, _prompt, _default in _REQUIRED_KEYS:
        if not (parsed.get(key, "").strip() or os.environ.get(key, "").strip()):
            return False
    return True


def _ask_value(
    *, prompt: str, default: str, secret: bool = False,
    asker: Callable[[str], str] | None = None,
) -> str:
    """单条提问；按回车采用默认；asker 可注入便于测试。"""
    ask = asker or _safe_input
    label = f"  {prompt}" + (f" [{default}]" if default else "")
    label += "（隐藏输入）" if secret else ""
    label += "：" if not label.endswith("：") else ""
    raw = ask(label + " ").strip()
    if not raw:
        return default
    return raw


def _write_env(env_path: Path, values: dict[str, str]) -> None:
    env_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by sanshiliu setup_wizard",
        "# 之后可手工编辑；建议保密不入版本库",
        "",
    ]
    for key, value in values.items():
        lines.append(f"{key}={value}")
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


async def _test_llm_connectivity(values: dict[str, str]) -> tuple[bool, str]:
    """简短调用一次目标 backend；失败回错误字符串。"""
    try:
        from openai import AsyncOpenAI
    except ImportError as exc:
        return False, f"无法导入 openai SDK：{exc}"

    client = AsyncOpenAI(
        api_key=values["OPENAI_API_KEY"],
        base_url=values["OPENAI_BASE_URL"],
    )
    import contextlib
    try:
        resp = await client.chat.completions.create(
            model=values["OPENAI_MODEL"],
            messages=[{"role": "user", "content": "ping"}],
            max_tokens=4,
            timeout=15.0,
        )
    except Exception as exc:
        return False, f"{type(exc).__name__}: {exc}"
    finally:
        with contextlib.suppress(Exception):
            await client.close()

    if not resp.choices:
        return False, "返回空 choices"
    return True, ""


async def run_setup_wizard(
    home_dir: Path,
    *,
    force: bool = False,
    asker: Callable[[str], str] | None = None,
    connectivity_check: Callable[[dict[str, str]], Awaitable[tuple[bool, str]]] | None = None,
) -> WizardResult | None:
    """env 完整时返回 None（无需向导）；否则交互填值 + 测试连通后落盘。

    asker / connectivity_check：测试可注入；生产用默认 input() + 真 LLM 调用。
    """
    env_path = home_dir / ".env"
    if not force and _is_env_complete(env_path):
        return None

    # async 函数里走同步 mkdir：bootstrap 启动期就一次，没必要拉 trio/anyio
    await asyncio.to_thread(_mkdir_parents, home_dir)
    print("\n── 首次启动向导 ──")
    print(f"  将把配置写入：{env_path}")

    values: dict[str, str] = {}
    for key, prompt, default in _REQUIRED_KEYS:
        existing = os.environ.get(key, "").strip()
        secret = (key == "OPENAI_API_KEY")
        value = _ask_value(
            prompt=prompt, default=existing or default, secret=secret, asker=asker,
        )
        if not value:
            print(f"  ❌ {key} 不能为空；向导取消")
            return WizardResult(env_path=env_path, values=values, llm_ok=False,
                                llm_error=f"{key} 留空")
        values[key] = value

    print("\n  测试 LLM 连通中 …")
    checker = connectivity_check or _test_llm_connectivity
    ok, err = await checker(values)
    if not ok:
        print(f"  ❌ LLM 不通：{err}")
        print("  继续启动？.env 不会写入，请回头检查 key / base_url / model。")
        return WizardResult(env_path=env_path, values=values, llm_ok=False, llm_error=err)

    _write_env(env_path, values)
    print(f"  ✅ LLM 连通；已写 {env_path}")
    _logger.info("setup_wizard 完成", env_path=str(env_path), model=values["OPENAI_MODEL"])
    return WizardResult(env_path=env_path, values=values, llm_ok=True)


def _safe_input(prompt: str) -> str:
    """input 包装；EOF/Ctrl-C 返空。"""
    try:
        return input(prompt)
    except (EOFError, KeyboardInterrupt):
        return ""
