"""首次启动向导；LLM 只提示模型名，wechat 缺凭据时走 Hermes QR 登录。"""

from __future__ import annotations

import asyncio
import os
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from pathlib import Path

from sanshiliu.bootstrap.wechat_setup import (
    DEFAULT_ACCOUNT_STORE,
    DEFAULT_QR_BOT_TYPE,
    DEFAULT_QR_FILE,
    DEFAULT_QR_TIMEOUT_SECONDS,
    ILINK_BASE_URL,
    run_wechat_channel_setup,
    wechat_channel_configured,
)
from sanshiliu.foundation.logging import get_logger


def _mkdir_parents(p: Path) -> None:
    """单独函数以便从 async 上下文用 to_thread 调度（绕 ASYNC240）。"""
    p.mkdir(parents=True, exist_ok=True)


_logger = get_logger(__name__)

# 只允许向导询问低敏字段；API key / base URL 必须由 .env 或进程环境提供。
_PROMPT_KEYS: tuple[tuple[str, str, str], ...] = (
    ("OPENAI_MODEL", "模型 ID（gpt-4o-mini / deepseek-chat / glm-4 等）", "gpt-4o-mini"),
)
_CONNECTIVITY_KEYS = ("OPENAI_API_KEY", "OPENAI_BASE_URL", "OPENAI_MODEL")
_WECHAT_KEYS = (
    "SANSHILIU_WECHAT_ENABLED",
    "ILINK_BASE_URL",
    "ILINK_API_KEY",
    "ILINK_WEBHOOK_SECRET",
    "WEIXIN_ACCOUNT_ID",
    "WEIXIN_TOKEN",
    "WEIXIN_BASE_URL",
    "WEIXIN_ACCOUNT_STORE",
    "WEIXIN_QR_FILE",
    "WEIXIN_QR_LOGIN",
    "WEIXIN_QR_BOT_TYPE",
    "WEIXIN_QR_TIMEOUT_SECONDS",
)
_DEFAULTS = {
    "OPENAI_BASE_URL": "https://api.openai.com/v1",
    "OPENAI_MODEL": "gpt-4o-mini",
    "WEIXIN_BASE_URL": ILINK_BASE_URL,
    "WEIXIN_ACCOUNT_STORE": DEFAULT_ACCOUNT_STORE,
    "WEIXIN_QR_FILE": DEFAULT_QR_FILE,
    "WEIXIN_QR_LOGIN": "true",
    "WEIXIN_QR_BOT_TYPE": DEFAULT_QR_BOT_TYPE,
    "WEIXIN_QR_TIMEOUT_SECONDS": str(DEFAULT_QR_TIMEOUT_SECONDS),
}


@dataclass
class WizardResult:
    """向导产出；values 含现有配置 + 向导采集的非敏感字段。"""

    env_path: Path
    values: dict[str, str]
    llm_ok: bool
    llm_error: str = ""
    completed: bool = True


def _read_env_file(env_path: Path) -> dict[str, str]:
    """读取简单 KEY=VALUE .env；不存在或坏行直接忽略。"""
    parsed: dict[str, str] = {}
    if env_path.is_file():
        text = env_path.read_text(encoding="utf-8")
        for line in text.splitlines():
            s = line.strip()
            if not s or s.startswith("#") or "=" not in s:
                continue
            k, _, v = s.partition("=")
            parsed[k.strip()] = v.strip().strip('"').strip("'")
    return parsed


def _collect_values(home_env_path: Path, project_env_path: Path | None) -> dict[str, str]:
    """按低到高优先级收集配置：默认值 < home env < project env < 进程 env。"""
    values = dict(_DEFAULTS)
    values.update(_read_env_file(home_env_path))
    if project_env_path is not None:
        values.update(_read_env_file(project_env_path))
    for key in (*_CONNECTIVITY_KEYS, *_WECHAT_KEYS):
        env_value = os.environ.get(key, "").strip()
        if env_value:
            values[key] = env_value
    for key, value in list(values.items()):
        if _is_placeholder_value(key, value):
            values[key] = ""
    return values


def _is_placeholder_value(key: str, value: str) -> bool:
    if key != "OPENAI_API_KEY":
        return False
    normalized = value.strip().lower()
    return normalized in {"sk-your-key-here", "your-key-here", "your-openai-api-key"}


def _is_env_complete(env_path: Path, project_env_path: Path | None = None) -> bool:
    """已有 LLM + wechat 配置都可用时返回 True；base URL 有默认值。"""
    values = _collect_values(env_path, project_env_path)
    for key in ("OPENAI_API_KEY", "OPENAI_MODEL"):
        if not values.get(key, "").strip():
            return False
    if values.get("WEIXIN_QR_LOGIN", "").strip().lower() in {"0", "false", "no", "off"}:
        return True
    return wechat_channel_configured(values)


def _ask_value(
    *,
    prompt: str,
    default: str,
    secret: bool = False,
    asker: Callable[[str], str] | None = None,
) -> str:
    """单条提问；按回车采用默认；asker 可注入便于测试。"""
    ask = asker or _safe_input
    label = f"  {prompt}" + (f" [{default}]" if default else "")
    label += "（隐藏输入）" if secret else ""
    label += "：" if not label.endswith("：") else ""
    raw = ask(label + " ").strip()
    if not raw:
        return default
    return raw


def _write_env(env_path: Path, values: dict[str, str]) -> None:
    """兼容旧调用：重写生成式 env。"""
    env_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by sanshiliu setup_wizard",
        "# 之后可手工编辑；建议保密不入版本库",
        "",
    ]
    for key, value in values.items():
        lines.append(f"{key}={value}")
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_env_updates(env_path: Path, updates: dict[str, str]) -> None:
    """保留现有 .env 注释与顺序，仅覆盖/追加需要更新的键。"""
    if not updates:
        return
    env_path.parent.mkdir(parents=True, exist_ok=True)
    existing_lines = env_path.read_text(encoding="utf-8").splitlines() if env_path.is_file() else []
    pending = dict(updates)
    lines: list[str] = []
    for line in existing_lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in line:
            lines.append(line)
            continue
        key, _, _ = line.partition("=")
        key = key.strip()
        if key in pending:
            lines.append(f"{key}={pending.pop(key)}")
        else:
            lines.append(line)

    if pending:
        if lines and lines[-1].strip():
            lines.append("")
        lines.append("# Added by sanshiliu setup_wizard")
        for key, value in pending.items():
            lines.append(f"{key}={value}")
    env_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


async def _test_llm_connectivity(values: dict[str, str]) -> tuple[bool, str]:
    """简短调用一次目标 backend；失败回错误字符串。"""
    try:
        from openai import AsyncOpenAI
    except ImportError as exc:
        return False, f"无法导入 openai SDK：{exc}"

    client = AsyncOpenAI(
        api_key=values["OPENAI_API_KEY"],
        base_url=values["OPENAI_BASE_URL"],
    )
    import contextlib

    try:
        resp = await client.chat.completions.create(
            model=values["OPENAI_MODEL"],
            messages=[{"role": "user", "content": "ping"}],
            max_tokens=4,
            timeout=15.0,
        )
    except Exception as exc:
        return False, f"{type(exc).__name__}: {exc}"
    finally:
        with contextlib.suppress(Exception):
            await client.close()

    if not resp.choices:
        return False, "返回空 choices"
    return True, ""


async def run_setup_wizard(
    home_dir: Path,
    *,
    force: bool = False,
    asker: Callable[[str], str] | None = None,
    connectivity_check: Callable[[dict[str, str]], Awaitable[tuple[bool, str]]] | None = None,
    project_env_path: Path | None = None,
) -> WizardResult | None:
    """env 完整时返回 None；否则只询问模型名，并用现有 key/base URL 测试连通。

    asker / connectivity_check：测试可注入；生产用默认 input() + 真 LLM 调用。
    """
    env_path = home_dir / ".env"
    project_root = project_env_path.parent if project_env_path is not None else Path.cwd()
    if not force and _is_env_complete(env_path, project_env_path):
        return None

    # async 函数里走同步 mkdir：bootstrap 启动期就一次，没必要拉 trio/anyio
    await asyncio.to_thread(_mkdir_parents, home_dir)
    print("\n── 首次启动向导 ──")
    print(f"  将把非敏感 LLM 配置写入：{env_path}")
    if project_env_path is not None:
        print(f"  WeChat 扫码凭据会写入项目 .env：{project_env_path}")
    print("  LLM API Key 和 base URL 请通过项目 .env 或进程环境变量提供。")

    values = _collect_values(env_path, project_env_path)
    prompted_values: dict[str, str] = {}
    for key, prompt, default in _PROMPT_KEYS:
        existing = values.get(key, "").strip()
        value = _ask_value(
            prompt=prompt,
            default=existing or default,
            secret=False,
            asker=asker,
        )
        if not value:
            print(f"  [ERROR] {key} 不能为空；向导取消")
            return WizardResult(
                env_path=env_path,
                values=values,
                llm_ok=False,
                llm_error=f"{key} 留空",
                completed=False,
            )
        values[key] = value
        prompted_values[key] = value

    home_updates = dict(prompted_values)
    project_updates: dict[str, str] = {}

    missing = [key for key in _CONNECTIVITY_KEYS if not values.get(key, "").strip()]
    if missing:
        msg = f"缺少 {', '.join(missing)}；请在项目 .env 或进程环境变量中配置"
        print(f"\n  [WARN] {msg}")
        print("  已跳过 LLM 连通测试。")
        llm_ok = False
        llm_error = msg
    else:
        print("\n  测试 LLM 连通中 …")
        checker = connectivity_check or _test_llm_connectivity
        llm_ok, llm_error = await checker(values)
        if not llm_ok:
            print(f"  [ERROR] LLM 不通：{llm_error}")
            print("  继续启动？请回头检查项目 .env 或进程环境变量。")
        else:
            print("  [OK] LLM 连通。")

    if not wechat_channel_configured(values) or force:
        wechat_updates = await run_wechat_channel_setup(values, project_root=project_root)
        if wechat_updates:
            values.update(wechat_updates)
            home_updates.update(wechat_updates)
            project_updates.update(wechat_updates)
    else:
        print("  WeChat：已发现可用配置，跳过二维码登录。")

    if home_updates:
        _write_env_updates(env_path, home_updates)
    if project_updates and project_env_path is not None:
        _write_env_updates(project_env_path, project_updates)

    if llm_ok:
        print(f"  [OK] setup 完成；已写 {env_path}")
    else:
        print(f"  [WARN] setup 已保存可用配置；LLM 仍需修复：{llm_error}")
    _logger.info(
        "setup_wizard 完成",
        env_path=str(env_path),
        project_env_path=str(project_env_path) if project_env_path else "",
        model=values["OPENAI_MODEL"],
        llm_ok=llm_ok,
    )
    return WizardResult(env_path=env_path, values=values, llm_ok=llm_ok, llm_error=llm_error)


def _safe_input(prompt: str) -> str:
    """input 包装；EOF/Ctrl-C 返空。"""
    try:
        return input(prompt)
    except (EOFError, KeyboardInterrupt):
        return ""
